version: latest

services:
  node-app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - PORT=3000
      - SERVER_NAME=Server 1

  node-app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      - PORT=3000
      - SERVER_NAME=Server 2
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app1
      - node-app2
